### ISSUE TITLE
the box is not available anymore 

### ISSUE THREAD

**Issue by tusharkhanka** [bchevallereau/ephesoft-vagrant#1]
The box 'chef/centos-6.5' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/chef/centos-6.5"]
Error: The requested URL returned error: 404 Not Found

i tried using bento/centos-6.5 but then fails to authenticate

**Comment by bchevallereau** [comment]
I had to update the Vagrant file to use a new VM definition. I updated as well the download link, and finally I added the missing properties in the silent install config.
